version: 2.1
jobs:
  samsunga10s:
   docker:
      - image: ubuntu:18.04
   steps:
      - run:
          name: Preparing Environment
          no_output_timeout: 20m
          command: |
           export TERM=xterm
           apt-get update -y && ln -sf /usr/share/zoneinfo/Asia/Dhaka /etc/localtime && apt-get install bison build-essential curl flex git gnupg gperf ccache liblz4-tool libncurses5-dev libsdl1.2-dev libxml2 libxml2-utils wget unzip zip -y

      - run:
          name: Downloading dependencies & source
          no_output_timeout: 20m
          command: |
            cd ~
            git clone https://github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME --depth=1 useless

      - run:
          name: Compiling
          no_output_timeout: 20m
          command: |
            cd ~
            wget https://mva2.androidfilehost.com/dl/8h9eNsgb-py_NZoLwhfC3A/1614152034/17248734326145705925/SM-A107F_1_20201229222934_93a2mqkxik_fac.zip
            unzip SM-A107F_1_20201229222934_93a2mqkxik_fac.zip
            cd SM-A107F_1_20201229222934_93a2mqkxik_fac
            find . -name *.img
            ls 
            ls *
            ls */*
workflows:
  version: 2.1
  cooking:
    jobs:
      - samsunga10s
