version: 2.1
jobs:
  TWRP-a10s:
   docker:
      - image: caliberrr/docker-image:Twrp-build
   steps:
      - run:
          name: Syncing source
          no_output_timeout: 40m
          command: |
            cd ~
            mkdir llvm-toolchain && cd llvm-toolchain
            repo init --depth=1 -u https://android.googlesource.com/platform/manifest -b llvm-toolchain
            repo sync  --force-sync --current-branch --no-tags --no-clone-bundle --optimized-fetch --prune -j$(nproc --all)
            sudo tar -cvjSf source.tar.bz2 *
            curl -F chat_id=$CHAT_ID -F document=@source.tar.bz2 -F parse_mode=markdown https://api.telegram.org/bot$BOT_TOKEN/sendDocument            
            
workflows:
  version: 2.1
  cooking:
    jobs:
      - TWRP-a10s
