version: 2.1
jobs:
  TWRP-a10s:
   docker:
      - image: caliberrr/docker-image:Twrp-build
   steps:
      - run:
          name: Syncing source
          no_output_timeout: 20m
          command: |
            cd ~
            mkdir twrp && cd twrp
            repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b twrp-9.0
            repo sync  --force-sync --current-branch --no-tags --no-clone-bundle --optimized-fetch --prune -j$(nproc --all)
            mkdir -p device/samsung && cd device/samsung
            git clone https://github.com/CaliBerrr/Twrp_device_samsung_a10s a10s
            git clone https://github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME useless
      - run:
          name: Building
          no_output_timeout: 20m
          command: |
            cd ~/twrp
            source build/envsetup.sh
            add_lunch_combo omni_a10sxx-eng
            export ALLOW_MISSING_DEPENDENCIES=true
            lunch omni_a10sxx-eng
            mka recoveryimage
      - run:
          name: Send To Telegram
          no_output_timeout: 20m
          command: |
            cd ~/twrp/out/target/product/a10s
            ZIPNAME="TWRP-$(date +%d_%m_%Y_%H_%M)-a10s.zip"
            sudo zip -r9 $ZIPNAME recovery.img
            curl -F chat_id=$CHAT_ID -F document=@$ZIPNAME -F parse_mode=markdown https://api.telegram.org/bot$BOT_TOKEN/sendDocument            
            
workflows:
  version: 2.1
  cooking:
    jobs:
      - TWRP-a10s
